/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.aldrin.ums.gui;

import com.aldrin.ums.controller.LoginController;
import com.aldrin.ums.entity.User;
import com.aldrin.ums.gui.dialog.JDialogChangePassword;
import com.aldrin.ums.gui.dialog.JDialogUser;
import com.aldrin.ums.gui.panel.JPanelAdmin;
import com.aldrin.ums.gui.panel.JPanelUser;
import com.formdev.flatlaf.FlatClientProperties;
import com.formdev.flatlaf.extras.FlatSVGIcon;
import java.awt.Color;

/**
 *
 * @author ALDRIN B. C.
 */
public class JFrameMain extends javax.swing.JFrame {

    /**
     * Creates new form JFrameMain
     */
    private JPanelAdmin panelAdmin = new JPanelAdmin();
    private JPanelUser panelUser = new JPanelUser();
    private User user;

    public JFrameMain() {
        initComponents();
        FlatSVGIcon icon = new FlatSVGIcon("svg/user.svg");
        setIconImage(icon.getImage());
        jPanelContainer.add(panelAdmin, "admin");
        jPanelContainer.add(panelUser, "user");
//        getRootPane().putClientProperty(FlatClientProperties.TITLE_BAR_BACKGROUND, new Color(70, 130, 180));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanelContainer = new javax.swing.JPanel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenuUser = new javax.swing.JMenu();
        jMenuItem2 = new javax.swing.JMenuItem();
        jMenuItem3 = new javax.swing.JMenuItem();
        jSeparator1 = new javax.swing.JPopupMenu.Separator();
        jMenuItem4 = new javax.swing.JMenuItem();
        jMenuSetup = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("UMS - User Management System");
        setResizable(false);

        jPanelContainer.setLayout(new java.awt.CardLayout());
        getContentPane().add(jPanelContainer, java.awt.BorderLayout.CENTER);

        jMenuUser.setIcon(new FlatSVGIcon("svg/user.svg"));
        jMenuUser.setText("File");

        jMenuItem2.setIcon(new FlatSVGIcon("svg/key.svg"));
        jMenuItem2.setText("Change Password");
        jMenuItem2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem2ActionPerformed(evt);
            }
        });
        jMenuUser.add(jMenuItem2);

        jMenuItem3.setIcon(new FlatSVGIcon("svg/logout.svg"));
        jMenuItem3.setText("Logout");
        jMenuItem3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem3ActionPerformed(evt);
            }
        });
        jMenuUser.add(jMenuItem3);
        jMenuUser.add(jSeparator1);

        jMenuItem4.setIcon(new FlatSVGIcon("svg/close.svg"));
        jMenuItem4.setText("Exit");
        jMenuItem4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem4ActionPerformed(evt);
            }
        });
        jMenuUser.add(jMenuItem4);

        jMenuBar1.add(jMenuUser);

        jMenuSetup.setIcon(new FlatSVGIcon("svg/setting.svg"));
        jMenuSetup.setText("Setup");

        jMenuItem1.setIcon(new FlatSVGIcon("svg/user setting.svg"));
        jMenuItem1.setText("User");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        jMenuSetup.add(jMenuItem1);

        jMenuBar1.add(jMenuSetup);

        setJMenuBar(jMenuBar1);

        setSize(new java.awt.Dimension(985, 495));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
        JDialogUser user = new JDialogUser(this, true);
        user.setVisible(true);
    }//GEN-LAST:event_jMenuItem1ActionPerformed

    private void jMenuItem3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem3ActionPerformed
        this.dispose();
        new LoginController(new JFrameLogin());
    }//GEN-LAST:event_jMenuItem3ActionPerformed

    private void jMenuItem2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem2ActionPerformed
      JDialogChangePassword changePassword=  new JDialogChangePassword(this, true,user);
      changePassword.setVisible(true);
        
    }//GEN-LAST:event_jMenuItem2ActionPerformed

    private void jMenuItem4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem4ActionPerformed
        System.exit(0);
    }//GEN-LAST:event_jMenuItem4ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(JFrameMain.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(JFrameMain.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(JFrameMain.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(JFrameMain.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new JFrameMain().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JMenuItem jMenuItem3;
    private javax.swing.JMenuItem jMenuItem4;
    private javax.swing.JMenu jMenuSetup;
    private javax.swing.JMenu jMenuUser;
    private javax.swing.JPanel jPanelContainer;
    private javax.swing.JPopupMenu.Separator jSeparator1;
    // End of variables declaration//GEN-END:variables

    /**
     * @return the jPanelContainer
     */
    public javax.swing.JPanel getjPanelContainer() {
        return jPanelContainer;
    }

    /**
     * @param jPanelContainer the jPanelContainer to set
     */
    public void setjPanelContainer(javax.swing.JPanel jPanelContainer) {
        this.jPanelContainer = jPanelContainer;
    }

    /**
     * @return the jMenuSetup
     */
    public javax.swing.JMenu getjMenuSetup() {
        return jMenuSetup;
    }

    /**
     * @param jMenuSetup the jMenuSetup to set
     */
    public void setjMenuSetup(javax.swing.JMenu jMenuSetup) {
        this.jMenuSetup = jMenuSetup;
    }

    /**
     * @return the jMenuUser
     */
    public javax.swing.JMenu getjMenuUser() {
        return jMenuUser;
    }

    /**
     * @param jMenuUser the jMenuUser to set
     */
    public void setjMenuUser(javax.swing.JMenu jMenuUser) {
        this.jMenuUser = jMenuUser;
    }

    /**
     * @return the user
     */
    public User getUser() {
        return user;
    }

    /**
     * @param user the user to set
     */
    public void setUser(User user) {
        this.user = user;
    }
}
