/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package com.aldrin.ums.gui.dialog.au;

import com.aldrin.ums.config.HibernateConfig;
import com.aldrin.ums.dao.impl.RoleDAOImpl;
import com.aldrin.ums.dao.impl.UserDAOImpl;
import com.aldrin.ums.entity.Role;
import com.aldrin.ums.entity.User;
import com.aldrin.ums.util.ComboBoxList;
import com.formdev.flatlaf.FlatClientProperties;
import com.formdev.flatlaf.extras.FlatSVGIcon;
import java.awt.Color;

/**
 *
 * @author ALDRIN B. C.
 */
public class JDialogUserAU extends javax.swing.JDialog {

    /**
     * Creates new form JDialogUserAU
     */
    private RoleDAOImpl roleDAOImpl = new RoleDAOImpl();
    private UserDAOImpl userDAOImpl = new UserDAOImpl();
    private HibernateConfig hibernateConfig = new HibernateConfig();
    private User user = new User();
    static String title = "";

    public JDialogUserAU(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        setTitle("New");
        comboBoxRole();
        this.title = "New";
        jButton1.setIcon(new FlatSVGIcon("svg/save.svg"));
        

    }
// update

    public JDialogUserAU(java.awt.Frame parent, boolean modal, User user, String title) {
        super(parent, modal);
        initComponents();
        setTitle("Update");
        jButton1.setText(title);
        this.user = user;
        this.title = title;
        jTextFieldFirstname.setText(user.getFirstname());
        jTextFieldSurname.setText(user.getSurname());
        jTextFieldUsername.setText(user.getUsername());
        jTextFieldPassword.setText(user.getPassword());
        comboBoxRole();
        for (ComboBoxList a : this.roleDAOImpl.getList()) {
            a.setSelectedId(roleDAOImpl.getList(), String.valueOf(user.getRole().getId()), jComboBoxRole);
        }
        jButton1.setIcon(new FlatSVGIcon("svg/update.svg"));
        
    }

    //delete
    public JDialogUserAU(java.awt.Frame parent, boolean modal, String title, User user) {
        super(parent, modal);
        initComponents();
        setTitle("Delete");
        jButton1.setText(title);
        this.user = user;
        this.title = title;
        jTextFieldFirstname.setText(user.getFirstname());
        jTextFieldSurname.setText(user.getSurname());
        jTextFieldUsername.setText(user.getUsername());
        jTextFieldPassword.setText(user.getPassword());
        comboBoxRole();
        for (ComboBoxList a : this.roleDAOImpl.getList()) {
            a.setSelectedId(roleDAOImpl.getList(), String.valueOf(user.getRole().getId()), jComboBoxRole);
        }
        jButton1.setIcon(new FlatSVGIcon("svg/delete.svg"));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jTextFieldPassword = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jTextFieldFirstname = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jTextFieldSurname = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jTextFieldUsername = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jComboBoxRole = new javax.swing.JComboBox<>();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setText("Role");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 210, 306, -1));

        jTextFieldPassword.setPreferredSize(new java.awt.Dimension(7, 28));
        getContentPane().add(jTextFieldPassword, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 175, 310, -1));

        jLabel2.setText("First name");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(12, 13, 306, -1));

        jTextFieldFirstname.setPreferredSize(new java.awt.Dimension(7, 28));
        getContentPane().add(jTextFieldFirstname, new org.netbeans.lib.awtextra.AbsoluteConstraints(12, 28, 310, -1));

        jLabel3.setText("Surname");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 60, 306, -1));

        jTextFieldSurname.setPreferredSize(new java.awt.Dimension(7, 28));
        getContentPane().add(jTextFieldSurname, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 75, 310, -1));

        jLabel4.setText("Username");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 110, 306, -1));

        jTextFieldUsername.setPreferredSize(new java.awt.Dimension(7, 28));
        getContentPane().add(jTextFieldUsername, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 125, 310, -1));

        jLabel5.setText("Password");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 160, 306, -1));

        jComboBoxRole.setPreferredSize(new java.awt.Dimension(306, 28));
        getContentPane().add(jComboBoxRole, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 230, 310, -1));

        jButton1.setText("Save");
        jButton1.setPreferredSize(new java.awt.Dimension(57, 32));
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 270, 210, -1));

        setSize(new java.awt.Dimension(350, 364));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        if (this.title.equals("New")) {
            this.user.setId(null);
            this.user.setFirstname(jTextFieldFirstname.getText());
            this.user.setSurname(jTextFieldSurname.getText());
            this.user.setUsername(jTextFieldUsername.getText());
            this.user.setPassword(jTextFieldPassword.getText());
            ComboBoxList roleId = (ComboBoxList) this.jComboBoxRole.getSelectedItem();
            Role role = new Role();
            role.setId(roleId.getId());
            user.setRole(role);
            userDAOImpl.addUser(user, hibernateConfig.getEntityManager());
            this.dispose();
        } else if (this.title.equals("Update")) {
            this.user.setId(user.getId());
            this.user.setFirstname(jTextFieldFirstname.getText());
            this.user.setSurname(jTextFieldSurname.getText());
            this.user.setUsername(jTextFieldUsername.getText());
            this.user.setPassword(jTextFieldPassword.getText());
            ComboBoxList roleId = (ComboBoxList) this.jComboBoxRole.getSelectedItem();
            Role role = new Role();
            role.setId(roleId.getId());
            user.setRole(role);
            userDAOImpl.updateUser(user, hibernateConfig.getEntityManager());
            this.dispose();
        } else if (this.title.equals("Delete")) {
            userDAOImpl.deleteUser(user, hibernateConfig.getEntityManager());
            this.dispose();
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(JDialogUserAU.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(JDialogUserAU.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(JDialogUserAU.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(JDialogUserAU.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                JDialogUserAU dialog = new JDialogUserAU(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JComboBox<Object> jComboBoxRole;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JTextField jTextFieldFirstname;
    private javax.swing.JTextField jTextFieldPassword;
    private javax.swing.JTextField jTextFieldSurname;
    private javax.swing.JTextField jTextFieldUsername;
    // End of variables declaration//GEN-END:variables
private void comboBoxRole() {
        roleDAOImpl.comboBoxRole(hibernateConfig.getEntityManager());
        jComboBoxRole.removeAllItems();
        for (ComboBoxList a : roleDAOImpl.getList()) {
            this.jComboBoxRole.addItem(a);
        }
    }

}
