/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package com.aldrin.ums.gui.panel;

import com.aldrin.ums.gui.JFrameMain;
import com.formdev.flatlaf.FlatClientProperties;
import com.formdev.flatlaf.extras.FlatSVGIcon;
import java.awt.Dimension;
import java.util.ArrayList;
import java.util.Date;
import java.util.List;
import org.jfree.chart.ChartFactory;
import org.jfree.chart.ChartPanel;
import org.jfree.chart.JFreeChart;
import org.jfree.chart.plot.PlotOrientation;
import org.jfree.data.category.CategoryDataset;
import org.jfree.data.category.DefaultCategoryDataset;
import org.jfree.data.gantt.Task;
import org.jfree.data.gantt.TaskSeries;
import org.jfree.data.gantt.TaskSeriesCollection;
import org.jfree.data.general.DefaultPieDataset;
import org.jfree.data.statistics.HistogramDataset;
import org.knowm.xchart.XChartPanel;
import org.knowm.xchart.XYChart;
import org.knowm.xchart.XYChartBuilder;
import org.knowm.xchart.style.Styler;
import org.knowm.xchart.style.markers.SeriesMarkers;

/**
 *
 * @author ALDRIN B. C.
 */
public class JPanelAdmin extends javax.swing.JPanel {

    /**
     * Creates new form JPanelAdmin
     */
    private JFrameMain jFrameMain;

    public JPanelAdmin() {
        initComponents();
        jPanel7.putClientProperty(FlatClientProperties.STYLE,
                "[light]border: 0,0,0,0,shade(@background,30%),,8;" + "[dark]border: 0,0,0,0,tint(@background,30%),,8");
        jPanel12.putClientProperty(FlatClientProperties.STYLE,
                "[light]border: 0,0,0,0,shade(@background,30%),,8;" + "[dark]border: 0,0,0,0,tint(@background,30%),,8");
        jPanel21.putClientProperty(FlatClientProperties.STYLE,
                "[light]border: 0,0,0,0,shade(@background,30%),,8;" + "[dark]border: 0,0,0,0,tint(@background,30%),,8");
        jPanelFrameBarChart.putClientProperty(FlatClientProperties.STYLE,
                "[light]border: 0,0,0,0,shade(@background,30%),,8;" + "[dark]border: 0,0,0,0,tint(@background,30%),,8");
        jPanelFramePieChart.putClientProperty(FlatClientProperties.STYLE,
                "[light]border: 0,0,0,0,shade(@background,30%),,8;" + "[dark]border: 0,0,0,0,tint(@background,30%),,8");
        jPanelFrameLineChart.putClientProperty(FlatClientProperties.STYLE,
                "[light]border: 0,0,0,0,shade(@background,30%),,8;" + "[dark]border: 0,0,0,0,tint(@background,30%),,8");
        jPanelFrameAreaChart.putClientProperty(FlatClientProperties.STYLE,
                "[light]border: 0,0,0,0,shade(@background,30%),,8;" + "[dark]border: 0,0,0,0,tint(@background,30%),,8");
        jPanelFrameWindChart.putClientProperty(FlatClientProperties.STYLE,
                "[light]border: 0,0,0,0,shade(@background,30%),,8;" + "[dark]border: 0,0,0,0,tint(@background,30%),,8");
        jPanelFrameGanttChart.putClientProperty(FlatClientProperties.STYLE,
                "[light]border: 0,0,0,0,shade(@background,30%),,8;" + "[dark]border: 0,0,0,0,tint(@background,30%),,8");

        intBarChart();
        initPieChart();
        initLineChart();
        initAreaChart();
        initHistogramChart();
        initGanttChart();

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel7 = new javax.swing.JPanel();
        jPanelFrameBarChart = new javax.swing.JPanel();
        jPanel24 = new javax.swing.JPanel();
        jPanelBarChart = new javax.swing.JPanel();
        jPanel5 = new javax.swing.JPanel();
        jPanel22 = new javax.swing.JPanel();
        jPanel23 = new javax.swing.JPanel();
        jPanelFramePieChart = new javax.swing.JPanel();
        jPanelPieChart = new javax.swing.JPanel();
        jPanel25 = new javax.swing.JPanel();
        jPanel26 = new javax.swing.JPanel();
        jPanel27 = new javax.swing.JPanel();
        jPanel28 = new javax.swing.JPanel();
        jPanelFrameLineChart = new javax.swing.JPanel();
        jPanelLineChart = new javax.swing.JPanel();
        jPanel8 = new javax.swing.JPanel();
        jPanel19 = new javax.swing.JPanel();
        jPanel20 = new javax.swing.JPanel();
        jPanel21 = new javax.swing.JPanel();
        jPanelFrameAreaChart = new javax.swing.JPanel();
        jPanelAreaChart = new javax.swing.JPanel();
        jPanel29 = new javax.swing.JPanel();
        jPanel30 = new javax.swing.JPanel();
        jPanel31 = new javax.swing.JPanel();
        jPanel32 = new javax.swing.JPanel();
        jPanelFrameWindChart = new javax.swing.JPanel();
        jPanelWindChart = new javax.swing.JPanel();
        jPanel33 = new javax.swing.JPanel();
        jPanel34 = new javax.swing.JPanel();
        jPanel35 = new javax.swing.JPanel();
        jPanel36 = new javax.swing.JPanel();
        jPanelFrameGanttChart = new javax.swing.JPanel();
        jPanelGanttChart = new javax.swing.JPanel();
        jPanel37 = new javax.swing.JPanel();
        jPanel38 = new javax.swing.JPanel();
        jPanel39 = new javax.swing.JPanel();
        jPanel40 = new javax.swing.JPanel();
        jPanel9 = new javax.swing.JPanel();
        jPanel10 = new javax.swing.JPanel();
        jPanel11 = new javax.swing.JPanel();
        jPanel6 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
        jPanel12 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jButton6 = new javax.swing.JButton();
        jButton7 = new javax.swing.JButton();
        jPanel13 = new javax.swing.JPanel();
        jPanel14 = new javax.swing.JPanel();
        jPanel15 = new javax.swing.JPanel();
        jPanel16 = new javax.swing.JPanel();
        jPanel17 = new javax.swing.JPanel();
        jPanel18 = new javax.swing.JPanel();

        setLayout(new java.awt.BorderLayout());

        jPanel1.setLayout(new java.awt.BorderLayout());

        jPanel7.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.LEFT, 10, 5));

        jPanelFrameBarChart.setPreferredSize(new java.awt.Dimension(260, 200));
        jPanelFrameBarChart.setLayout(new java.awt.BorderLayout());

        jPanel24.setOpaque(false);
        jPanel24.setPreferredSize(new java.awt.Dimension(2, 2));

        javax.swing.GroupLayout jPanel24Layout = new javax.swing.GroupLayout(jPanel24);
        jPanel24.setLayout(jPanel24Layout);
        jPanel24Layout.setHorizontalGroup(
            jPanel24Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        jPanel24Layout.setVerticalGroup(
            jPanel24Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        jPanelFrameBarChart.add(jPanel24, java.awt.BorderLayout.WEST);

        jPanelBarChart.setOpaque(false);
        jPanelBarChart.setPreferredSize(new java.awt.Dimension(270, 200));
        jPanelBarChart.setLayout(new java.awt.BorderLayout());
        jPanelFrameBarChart.add(jPanelBarChart, java.awt.BorderLayout.CENTER);

        jPanel5.setOpaque(false);
        jPanel5.setPreferredSize(new java.awt.Dimension(270, 2));

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 260, Short.MAX_VALUE)
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 2, Short.MAX_VALUE)
        );

        jPanelFrameBarChart.add(jPanel5, java.awt.BorderLayout.NORTH);

        jPanel22.setOpaque(false);
        jPanel22.setPreferredSize(new java.awt.Dimension(270, 2));

        javax.swing.GroupLayout jPanel22Layout = new javax.swing.GroupLayout(jPanel22);
        jPanel22.setLayout(jPanel22Layout);
        jPanel22Layout.setHorizontalGroup(
            jPanel22Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 260, Short.MAX_VALUE)
        );
        jPanel22Layout.setVerticalGroup(
            jPanel22Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 2, Short.MAX_VALUE)
        );

        jPanelFrameBarChart.add(jPanel22, java.awt.BorderLayout.SOUTH);

        jPanel23.setOpaque(false);
        jPanel23.setPreferredSize(new java.awt.Dimension(2, 2));

        javax.swing.GroupLayout jPanel23Layout = new javax.swing.GroupLayout(jPanel23);
        jPanel23.setLayout(jPanel23Layout);
        jPanel23Layout.setHorizontalGroup(
            jPanel23Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 2, Short.MAX_VALUE)
        );
        jPanel23Layout.setVerticalGroup(
            jPanel23Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 196, Short.MAX_VALUE)
        );

        jPanelFrameBarChart.add(jPanel23, java.awt.BorderLayout.EAST);

        jPanel7.add(jPanelFrameBarChart);

        jPanelFramePieChart.setPreferredSize(new java.awt.Dimension(260, 200));
        jPanelFramePieChart.setLayout(new java.awt.BorderLayout());

        jPanelPieChart.setPreferredSize(new java.awt.Dimension(270, 200));
        jPanelPieChart.setLayout(new java.awt.BorderLayout());
        jPanelFramePieChart.add(jPanelPieChart, java.awt.BorderLayout.CENTER);

        jPanel25.setOpaque(false);
        jPanel25.setPreferredSize(new java.awt.Dimension(270, 2));

        javax.swing.GroupLayout jPanel25Layout = new javax.swing.GroupLayout(jPanel25);
        jPanel25.setLayout(jPanel25Layout);
        jPanel25Layout.setHorizontalGroup(
            jPanel25Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 260, Short.MAX_VALUE)
        );
        jPanel25Layout.setVerticalGroup(
            jPanel25Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 2, Short.MAX_VALUE)
        );

        jPanelFramePieChart.add(jPanel25, java.awt.BorderLayout.NORTH);

        jPanel26.setOpaque(false);
        jPanel26.setPreferredSize(new java.awt.Dimension(270, 2));

        javax.swing.GroupLayout jPanel26Layout = new javax.swing.GroupLayout(jPanel26);
        jPanel26.setLayout(jPanel26Layout);
        jPanel26Layout.setHorizontalGroup(
            jPanel26Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 260, Short.MAX_VALUE)
        );
        jPanel26Layout.setVerticalGroup(
            jPanel26Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 2, Short.MAX_VALUE)
        );

        jPanelFramePieChart.add(jPanel26, java.awt.BorderLayout.SOUTH);

        jPanel27.setOpaque(false);
        jPanel27.setPreferredSize(new java.awt.Dimension(2, 2));

        javax.swing.GroupLayout jPanel27Layout = new javax.swing.GroupLayout(jPanel27);
        jPanel27.setLayout(jPanel27Layout);
        jPanel27Layout.setHorizontalGroup(
            jPanel27Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 2, Short.MAX_VALUE)
        );
        jPanel27Layout.setVerticalGroup(
            jPanel27Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 196, Short.MAX_VALUE)
        );

        jPanelFramePieChart.add(jPanel27, java.awt.BorderLayout.EAST);

        jPanel28.setOpaque(false);
        jPanel28.setPreferredSize(new java.awt.Dimension(2, 2));

        javax.swing.GroupLayout jPanel28Layout = new javax.swing.GroupLayout(jPanel28);
        jPanel28.setLayout(jPanel28Layout);
        jPanel28Layout.setHorizontalGroup(
            jPanel28Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 2, Short.MAX_VALUE)
        );
        jPanel28Layout.setVerticalGroup(
            jPanel28Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 196, Short.MAX_VALUE)
        );

        jPanelFramePieChart.add(jPanel28, java.awt.BorderLayout.WEST);

        jPanel7.add(jPanelFramePieChart);

        jPanelFrameLineChart.setPreferredSize(new java.awt.Dimension(260, 200));
        jPanelFrameLineChart.setLayout(new java.awt.BorderLayout());

        jPanelLineChart.setPreferredSize(new java.awt.Dimension(260, 0));
        jPanelLineChart.setLayout(new java.awt.BorderLayout());
        jPanelFrameLineChart.add(jPanelLineChart, java.awt.BorderLayout.CENTER);

        jPanel8.setOpaque(false);
        jPanel8.setPreferredSize(new java.awt.Dimension(270, 2));

        javax.swing.GroupLayout jPanel8Layout = new javax.swing.GroupLayout(jPanel8);
        jPanel8.setLayout(jPanel8Layout);
        jPanel8Layout.setHorizontalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 260, Short.MAX_VALUE)
        );
        jPanel8Layout.setVerticalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 2, Short.MAX_VALUE)
        );

        jPanelFrameLineChart.add(jPanel8, java.awt.BorderLayout.NORTH);

        jPanel19.setOpaque(false);
        jPanel19.setPreferredSize(new java.awt.Dimension(270, 2));

        javax.swing.GroupLayout jPanel19Layout = new javax.swing.GroupLayout(jPanel19);
        jPanel19.setLayout(jPanel19Layout);
        jPanel19Layout.setHorizontalGroup(
            jPanel19Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 260, Short.MAX_VALUE)
        );
        jPanel19Layout.setVerticalGroup(
            jPanel19Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 2, Short.MAX_VALUE)
        );

        jPanelFrameLineChart.add(jPanel19, java.awt.BorderLayout.SOUTH);

        jPanel20.setOpaque(false);
        jPanel20.setPreferredSize(new java.awt.Dimension(2, 0));

        javax.swing.GroupLayout jPanel20Layout = new javax.swing.GroupLayout(jPanel20);
        jPanel20.setLayout(jPanel20Layout);
        jPanel20Layout.setHorizontalGroup(
            jPanel20Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 2, Short.MAX_VALUE)
        );
        jPanel20Layout.setVerticalGroup(
            jPanel20Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        jPanelFrameLineChart.add(jPanel20, java.awt.BorderLayout.EAST);

        jPanel21.setOpaque(false);
        jPanel21.setPreferredSize(new java.awt.Dimension(2, 0));

        javax.swing.GroupLayout jPanel21Layout = new javax.swing.GroupLayout(jPanel21);
        jPanel21.setLayout(jPanel21Layout);
        jPanel21Layout.setHorizontalGroup(
            jPanel21Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 2, Short.MAX_VALUE)
        );
        jPanel21Layout.setVerticalGroup(
            jPanel21Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        jPanelFrameLineChart.add(jPanel21, java.awt.BorderLayout.WEST);

        jPanel7.add(jPanelFrameLineChart);

        jPanelFrameAreaChart.setPreferredSize(new java.awt.Dimension(260, 200));
        jPanelFrameAreaChart.setLayout(new java.awt.BorderLayout());

        jPanelAreaChart.setPreferredSize(new java.awt.Dimension(260, 0));
        jPanelAreaChart.setLayout(new java.awt.BorderLayout());
        jPanelFrameAreaChart.add(jPanelAreaChart, java.awt.BorderLayout.CENTER);

        jPanel29.setOpaque(false);
        jPanel29.setPreferredSize(new java.awt.Dimension(270, 2));

        javax.swing.GroupLayout jPanel29Layout = new javax.swing.GroupLayout(jPanel29);
        jPanel29.setLayout(jPanel29Layout);
        jPanel29Layout.setHorizontalGroup(
            jPanel29Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 260, Short.MAX_VALUE)
        );
        jPanel29Layout.setVerticalGroup(
            jPanel29Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 2, Short.MAX_VALUE)
        );

        jPanelFrameAreaChart.add(jPanel29, java.awt.BorderLayout.NORTH);

        jPanel30.setOpaque(false);
        jPanel30.setPreferredSize(new java.awt.Dimension(270, 2));

        javax.swing.GroupLayout jPanel30Layout = new javax.swing.GroupLayout(jPanel30);
        jPanel30.setLayout(jPanel30Layout);
        jPanel30Layout.setHorizontalGroup(
            jPanel30Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 260, Short.MAX_VALUE)
        );
        jPanel30Layout.setVerticalGroup(
            jPanel30Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 2, Short.MAX_VALUE)
        );

        jPanelFrameAreaChart.add(jPanel30, java.awt.BorderLayout.SOUTH);

        jPanel31.setOpaque(false);
        jPanel31.setPreferredSize(new java.awt.Dimension(2, 0));

        javax.swing.GroupLayout jPanel31Layout = new javax.swing.GroupLayout(jPanel31);
        jPanel31.setLayout(jPanel31Layout);
        jPanel31Layout.setHorizontalGroup(
            jPanel31Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 2, Short.MAX_VALUE)
        );
        jPanel31Layout.setVerticalGroup(
            jPanel31Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        jPanelFrameAreaChart.add(jPanel31, java.awt.BorderLayout.EAST);

        jPanel32.setOpaque(false);
        jPanel32.setPreferredSize(new java.awt.Dimension(2, 0));

        javax.swing.GroupLayout jPanel32Layout = new javax.swing.GroupLayout(jPanel32);
        jPanel32.setLayout(jPanel32Layout);
        jPanel32Layout.setHorizontalGroup(
            jPanel32Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 2, Short.MAX_VALUE)
        );
        jPanel32Layout.setVerticalGroup(
            jPanel32Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        jPanelFrameAreaChart.add(jPanel32, java.awt.BorderLayout.WEST);

        jPanel7.add(jPanelFrameAreaChart);

        jPanelFrameWindChart.setPreferredSize(new java.awt.Dimension(260, 200));
        jPanelFrameWindChart.setLayout(new java.awt.BorderLayout());

        jPanelWindChart.setPreferredSize(new java.awt.Dimension(260, 0));
        jPanelWindChart.setLayout(new java.awt.BorderLayout());
        jPanelFrameWindChart.add(jPanelWindChart, java.awt.BorderLayout.CENTER);

        jPanel33.setOpaque(false);
        jPanel33.setPreferredSize(new java.awt.Dimension(270, 2));

        javax.swing.GroupLayout jPanel33Layout = new javax.swing.GroupLayout(jPanel33);
        jPanel33.setLayout(jPanel33Layout);
        jPanel33Layout.setHorizontalGroup(
            jPanel33Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 260, Short.MAX_VALUE)
        );
        jPanel33Layout.setVerticalGroup(
            jPanel33Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 2, Short.MAX_VALUE)
        );

        jPanelFrameWindChart.add(jPanel33, java.awt.BorderLayout.NORTH);

        jPanel34.setOpaque(false);
        jPanel34.setPreferredSize(new java.awt.Dimension(270, 2));

        javax.swing.GroupLayout jPanel34Layout = new javax.swing.GroupLayout(jPanel34);
        jPanel34.setLayout(jPanel34Layout);
        jPanel34Layout.setHorizontalGroup(
            jPanel34Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 260, Short.MAX_VALUE)
        );
        jPanel34Layout.setVerticalGroup(
            jPanel34Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 2, Short.MAX_VALUE)
        );

        jPanelFrameWindChart.add(jPanel34, java.awt.BorderLayout.SOUTH);

        jPanel35.setOpaque(false);
        jPanel35.setPreferredSize(new java.awt.Dimension(2, 0));

        javax.swing.GroupLayout jPanel35Layout = new javax.swing.GroupLayout(jPanel35);
        jPanel35.setLayout(jPanel35Layout);
        jPanel35Layout.setHorizontalGroup(
            jPanel35Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 2, Short.MAX_VALUE)
        );
        jPanel35Layout.setVerticalGroup(
            jPanel35Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        jPanelFrameWindChart.add(jPanel35, java.awt.BorderLayout.EAST);

        jPanel36.setOpaque(false);
        jPanel36.setPreferredSize(new java.awt.Dimension(2, 0));

        javax.swing.GroupLayout jPanel36Layout = new javax.swing.GroupLayout(jPanel36);
        jPanel36.setLayout(jPanel36Layout);
        jPanel36Layout.setHorizontalGroup(
            jPanel36Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 2, Short.MAX_VALUE)
        );
        jPanel36Layout.setVerticalGroup(
            jPanel36Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        jPanelFrameWindChart.add(jPanel36, java.awt.BorderLayout.WEST);

        jPanel7.add(jPanelFrameWindChart);

        jPanelFrameGanttChart.setPreferredSize(new java.awt.Dimension(260, 200));
        jPanelFrameGanttChart.setLayout(new java.awt.BorderLayout());

        jPanelGanttChart.setPreferredSize(new java.awt.Dimension(260, 0));
        jPanelGanttChart.setLayout(new java.awt.BorderLayout());
        jPanelFrameGanttChart.add(jPanelGanttChart, java.awt.BorderLayout.CENTER);

        jPanel37.setOpaque(false);
        jPanel37.setPreferredSize(new java.awt.Dimension(270, 2));

        javax.swing.GroupLayout jPanel37Layout = new javax.swing.GroupLayout(jPanel37);
        jPanel37.setLayout(jPanel37Layout);
        jPanel37Layout.setHorizontalGroup(
            jPanel37Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 260, Short.MAX_VALUE)
        );
        jPanel37Layout.setVerticalGroup(
            jPanel37Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 2, Short.MAX_VALUE)
        );

        jPanelFrameGanttChart.add(jPanel37, java.awt.BorderLayout.NORTH);

        jPanel38.setOpaque(false);
        jPanel38.setPreferredSize(new java.awt.Dimension(270, 2));

        javax.swing.GroupLayout jPanel38Layout = new javax.swing.GroupLayout(jPanel38);
        jPanel38.setLayout(jPanel38Layout);
        jPanel38Layout.setHorizontalGroup(
            jPanel38Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 260, Short.MAX_VALUE)
        );
        jPanel38Layout.setVerticalGroup(
            jPanel38Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 2, Short.MAX_VALUE)
        );

        jPanelFrameGanttChart.add(jPanel38, java.awt.BorderLayout.SOUTH);

        jPanel39.setOpaque(false);
        jPanel39.setPreferredSize(new java.awt.Dimension(2, 0));

        javax.swing.GroupLayout jPanel39Layout = new javax.swing.GroupLayout(jPanel39);
        jPanel39.setLayout(jPanel39Layout);
        jPanel39Layout.setHorizontalGroup(
            jPanel39Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 2, Short.MAX_VALUE)
        );
        jPanel39Layout.setVerticalGroup(
            jPanel39Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        jPanelFrameGanttChart.add(jPanel39, java.awt.BorderLayout.EAST);

        jPanel40.setOpaque(false);
        jPanel40.setPreferredSize(new java.awt.Dimension(2, 0));

        javax.swing.GroupLayout jPanel40Layout = new javax.swing.GroupLayout(jPanel40);
        jPanel40.setLayout(jPanel40Layout);
        jPanel40Layout.setHorizontalGroup(
            jPanel40Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 2, Short.MAX_VALUE)
        );
        jPanel40Layout.setVerticalGroup(
            jPanel40Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        jPanelFrameGanttChart.add(jPanel40, java.awt.BorderLayout.WEST);

        jPanel7.add(jPanelFrameGanttChart);

        jPanel1.add(jPanel7, java.awt.BorderLayout.CENTER);

        jPanel9.setPreferredSize(new java.awt.Dimension(667, 5));

        javax.swing.GroupLayout jPanel9Layout = new javax.swing.GroupLayout(jPanel9);
        jPanel9.setLayout(jPanel9Layout);
        jPanel9Layout.setHorizontalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        jPanel9Layout.setVerticalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 5, Short.MAX_VALUE)
        );

        jPanel1.add(jPanel9, java.awt.BorderLayout.SOUTH);

        jPanel10.setPreferredSize(new java.awt.Dimension(5, 547));

        javax.swing.GroupLayout jPanel10Layout = new javax.swing.GroupLayout(jPanel10);
        jPanel10.setLayout(jPanel10Layout);
        jPanel10Layout.setHorizontalGroup(
            jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 5, Short.MAX_VALUE)
        );
        jPanel10Layout.setVerticalGroup(
            jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 514, Short.MAX_VALUE)
        );

        jPanel1.add(jPanel10, java.awt.BorderLayout.EAST);

        jPanel11.setPreferredSize(new java.awt.Dimension(5, 547));

        javax.swing.GroupLayout jPanel11Layout = new javax.swing.GroupLayout(jPanel11);
        jPanel11.setLayout(jPanel11Layout);
        jPanel11Layout.setHorizontalGroup(
            jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 5, Short.MAX_VALUE)
        );
        jPanel11Layout.setVerticalGroup(
            jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 514, Short.MAX_VALUE)
        );

        jPanel1.add(jPanel11, java.awt.BorderLayout.LINE_START);

        add(jPanel1, java.awt.BorderLayout.CENTER);

        jPanel6.setLayout(new java.awt.BorderLayout());

        jPanel2.setPreferredSize(new java.awt.Dimension(130, 364));
        jPanel2.setLayout(new java.awt.BorderLayout());

        jPanel4.setPreferredSize(new java.awt.Dimension(100, 200));
        jPanel4.setLayout(new java.awt.BorderLayout());

        jPanel12.setPreferredSize(new java.awt.Dimension(95, 200));
        jPanel12.setLayout(new java.awt.BorderLayout());

        jPanel3.setOpaque(false);
        jPanel3.setLayout(new java.awt.GridLayout(0, 1));

        jButton1.setIcon(new FlatSVGIcon("svg/dashboard.svg"));
        jButton1.setText("Dashboard");
        jButton1.setBorder(null);
        jButton1.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jButton1.setMargin(new java.awt.Insets(2, 5, 2, 2));
        jPanel3.add(jButton1);

        jButton2.setIcon(new FlatSVGIcon("svg/analytics.svg"));
        jButton2.setText("Analytics");
        jButton2.setBorder(null);
        jButton2.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jButton2.setMargin(new java.awt.Insets(2, 5, 2, 2));
        jPanel3.add(jButton2);

        jButton3.setIcon(new FlatSVGIcon("svg/sale.svg"));
        jButton3.setText("Sales");
        jButton3.setBorder(null);
        jButton3.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jButton3.setMargin(new java.awt.Insets(2, 5, 2, 2));
        jPanel3.add(jButton3);

        jButton5.setIcon(new FlatSVGIcon("svg/order.svg"));
        jButton5.setText("Orders");
        jButton5.setBorder(null);
        jButton5.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jButton5.setMargin(new java.awt.Insets(2, 5, 2, 2));
        jPanel3.add(jButton5);

        jButton6.setIcon(new FlatSVGIcon("svg/maintenance.svg"));
        jButton6.setText("Maintenance");
        jButton6.setBorder(null);
        jButton6.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jButton6.setMargin(new java.awt.Insets(2, 5, 2, 2));
        jPanel3.add(jButton6);

        jButton7.setIcon(new FlatSVGIcon("svg/config.svg"));
        jButton7.setText("Configuration");
        jButton7.setBorder(null);
        jButton7.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jButton7.setMargin(new java.awt.Insets(2, 5, 2, 2));
        jPanel3.add(jButton7);

        jPanel12.add(jPanel3, java.awt.BorderLayout.CENTER);

        jPanel13.setOpaque(false);
        jPanel13.setPreferredSize(new java.awt.Dimension(95, 1));

        javax.swing.GroupLayout jPanel13Layout = new javax.swing.GroupLayout(jPanel13);
        jPanel13.setLayout(jPanel13Layout);
        jPanel13Layout.setHorizontalGroup(
            jPanel13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 130, Short.MAX_VALUE)
        );
        jPanel13Layout.setVerticalGroup(
            jPanel13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        jPanel12.add(jPanel13, java.awt.BorderLayout.NORTH);

        jPanel14.setOpaque(false);
        jPanel14.setPreferredSize(new java.awt.Dimension(95, 3));

        javax.swing.GroupLayout jPanel14Layout = new javax.swing.GroupLayout(jPanel14);
        jPanel14.setLayout(jPanel14Layout);
        jPanel14Layout.setHorizontalGroup(
            jPanel14Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 130, Short.MAX_VALUE)
        );
        jPanel14Layout.setVerticalGroup(
            jPanel14Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 3, Short.MAX_VALUE)
        );

        jPanel12.add(jPanel14, java.awt.BorderLayout.SOUTH);

        jPanel15.setOpaque(false);
        jPanel15.setPreferredSize(new java.awt.Dimension(3, 442));

        javax.swing.GroupLayout jPanel15Layout = new javax.swing.GroupLayout(jPanel15);
        jPanel15.setLayout(jPanel15Layout);
        jPanel15Layout.setHorizontalGroup(
            jPanel15Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 3, Short.MAX_VALUE)
        );
        jPanel15Layout.setVerticalGroup(
            jPanel15Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 196, Short.MAX_VALUE)
        );

        jPanel12.add(jPanel15, java.awt.BorderLayout.EAST);

        jPanel16.setOpaque(false);
        jPanel16.setPreferredSize(new java.awt.Dimension(3, 442));

        javax.swing.GroupLayout jPanel16Layout = new javax.swing.GroupLayout(jPanel16);
        jPanel16.setLayout(jPanel16Layout);
        jPanel16Layout.setHorizontalGroup(
            jPanel16Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 3, Short.MAX_VALUE)
        );
        jPanel16Layout.setVerticalGroup(
            jPanel16Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 196, Short.MAX_VALUE)
        );

        jPanel12.add(jPanel16, java.awt.BorderLayout.WEST);

        jPanel4.add(jPanel12, java.awt.BorderLayout.SOUTH);

        jPanel17.setPreferredSize(new java.awt.Dimension(100, 3));

        javax.swing.GroupLayout jPanel17Layout = new javax.swing.GroupLayout(jPanel17);
        jPanel17.setLayout(jPanel17Layout);
        jPanel17Layout.setHorizontalGroup(
            jPanel17Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 130, Short.MAX_VALUE)
        );
        jPanel17Layout.setVerticalGroup(
            jPanel17Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 3, Short.MAX_VALUE)
        );

        jPanel4.add(jPanel17, java.awt.BorderLayout.NORTH);

        jPanel2.add(jPanel4, java.awt.BorderLayout.NORTH);

        jPanel6.add(jPanel2, java.awt.BorderLayout.EAST);

        jPanel18.setPreferredSize(new java.awt.Dimension(2, 519));

        javax.swing.GroupLayout jPanel18Layout = new javax.swing.GroupLayout(jPanel18);
        jPanel18.setLayout(jPanel18Layout);
        jPanel18Layout.setHorizontalGroup(
            jPanel18Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 2, Short.MAX_VALUE)
        );
        jPanel18Layout.setVerticalGroup(
            jPanel18Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 519, Short.MAX_VALUE)
        );

        jPanel6.add(jPanel18, java.awt.BorderLayout.WEST);

        add(jPanel6, java.awt.BorderLayout.WEST);
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel10;
    private javax.swing.JPanel jPanel11;
    private javax.swing.JPanel jPanel12;
    private javax.swing.JPanel jPanel13;
    private javax.swing.JPanel jPanel14;
    private javax.swing.JPanel jPanel15;
    private javax.swing.JPanel jPanel16;
    private javax.swing.JPanel jPanel17;
    private javax.swing.JPanel jPanel18;
    private javax.swing.JPanel jPanel19;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel20;
    private javax.swing.JPanel jPanel21;
    private javax.swing.JPanel jPanel22;
    private javax.swing.JPanel jPanel23;
    private javax.swing.JPanel jPanel24;
    private javax.swing.JPanel jPanel25;
    private javax.swing.JPanel jPanel26;
    private javax.swing.JPanel jPanel27;
    private javax.swing.JPanel jPanel28;
    private javax.swing.JPanel jPanel29;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel30;
    private javax.swing.JPanel jPanel31;
    private javax.swing.JPanel jPanel32;
    private javax.swing.JPanel jPanel33;
    private javax.swing.JPanel jPanel34;
    private javax.swing.JPanel jPanel35;
    private javax.swing.JPanel jPanel36;
    private javax.swing.JPanel jPanel37;
    private javax.swing.JPanel jPanel38;
    private javax.swing.JPanel jPanel39;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel40;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JPanel jPanel9;
    private javax.swing.JPanel jPanelAreaChart;
    private javax.swing.JPanel jPanelBarChart;
    private javax.swing.JPanel jPanelFrameAreaChart;
    private javax.swing.JPanel jPanelFrameBarChart;
    private javax.swing.JPanel jPanelFrameGanttChart;
    private javax.swing.JPanel jPanelFrameLineChart;
    private javax.swing.JPanel jPanelFramePieChart;
    private javax.swing.JPanel jPanelFrameWindChart;
    private javax.swing.JPanel jPanelGanttChart;
    private javax.swing.JPanel jPanelLineChart;
    private javax.swing.JPanel jPanelPieChart;
    private javax.swing.JPanel jPanelWindChart;
    // End of variables declaration//GEN-END:variables
      private void intBarChart() {
        CategoryDataset dataset = createDatasetForBarChart();

        // Create chart
        JFreeChart chart = ChartFactory.createBarChart(
                "Product Sales",
                "Category",
                "Value",
                dataset
        );

        // Create Panel
        ChartPanel chartPanel = new ChartPanel(chart);
        chartPanel.setPreferredSize(new Dimension(560, 370));
        jPanelBarChart.add(chartPanel);

    }

    private CategoryDataset createDatasetForBarChart() {
        DefaultCategoryDataset dataset = new DefaultCategoryDataset();

        // Add data to the dataset
        dataset.addValue(100.0, "PREVIOUS", "AUG");
        dataset.addValue(400.0, "PREVIOUS", "SEP");
        dataset.addValue(300.0, "PREVIOUS", "OCT");
        dataset.addValue(500.0, "PREVIOUS", "NOV");

        dataset.addValue(500.0, "CURRENT", "AUG");
        dataset.addValue(700.0, "CURRENT", "SEP");
        dataset.addValue(600.0, "CURRENT", "OCT");
        dataset.addValue(800.0, "CURRENT", "NOV");

        return dataset;
    }

    private void initPieChart() {
        DefaultPieDataset dataset = createDatasetForPieChart();

        // Create chart
        JFreeChart chart = ChartFactory.createPieChart(
                "Products Status",
                dataset,
                true, // include legend
                true,
                false
        );

        // Create Panel
        ChartPanel chartPanel = new ChartPanel(chart);
        chartPanel.setPreferredSize(new Dimension(560, 370));
        chartPanel.setOpaque(false);
        jPanelPieChart.add(chartPanel);

    }

    private DefaultPieDataset createDatasetForPieChart() {
        DefaultPieDataset dataset = new DefaultPieDataset();

        // Add data to the dataset
        dataset.setValue("Grocery", 40);
        dataset.setValue("Cosmitics", 25);
        dataset.setValue("Drinks", 20);
        dataset.setValue("Snacks", 15);

        return dataset;
    }

    private void initLineChart() {
        CategoryDataset dataset = createDatasetForLineChart();

        // Create chart
        JFreeChart chart = ChartFactory.createLineChart(
                "Product Stocks",
                "Category",
                "Value",
                dataset
        );

        // Create Panel
        ChartPanel chartPanel = new ChartPanel(chart);
        chartPanel.setPreferredSize(new Dimension(560, 370));
        jPanelLineChart.add(chartPanel);
    }

    private CategoryDataset createDatasetForLineChart() {
        DefaultCategoryDataset dataset = new DefaultCategoryDataset();

        // Add data to the dataset
        dataset.addValue(10.0, "Damaged", "Grocery");
        dataset.addValue(40.0, "Damaged", "Cosmitics");
        dataset.addValue(30.0, "Damaged", "Drinks");
        dataset.addValue(50.0, "Damaged", "Snacks");

        dataset.addValue(50.0, "Expired", "Grocery");
        dataset.addValue(70.0, "Expired", "Cosmitics");
        dataset.addValue(60.0, "Expired", "Drinks");
        dataset.addValue(80.0, "Expired", "Snacks");

        return dataset;
    }

    private void initAreaChart() {
        CategoryDataset dataset = createDatasetForLineChart();

        // Create chart
        JFreeChart chart = ChartFactory.createAreaChart(
                "Product Orders",
                "Category",
                "Value",
                dataset
        );

        // Create Panel
        ChartPanel chartPanel = new ChartPanel(chart);
        chartPanel.setPreferredSize(new Dimension(560, 370));
        jPanelAreaChart.add(chartPanel);

    }

    private CategoryDataset createDatasetAreaChart() {
        DefaultCategoryDataset dataset = new DefaultCategoryDataset();

        // Add data to the dataset
        dataset.addValue(1.0, "Series 1", "Category 1");
        dataset.addValue(4.0, "Series 1", "Category 2");
        dataset.addValue(3.0, "Series 1", "Category 3");
        dataset.addValue(5.0, "Series 1", "Category 4");

        dataset.addValue(5.0, "Series 2", "Category 1");
        dataset.addValue(7.0, "Series 2", "Category 2");
        dataset.addValue(6.0, "Series 2", "Category 3");
        dataset.addValue(8.0, "Series 2", "Category 4");

        return dataset;
    }

    private void initWindChart() {
        List<Double> windSpeedData = new ArrayList<>();
        List<Double> windDirectionData = new ArrayList<>();

        // Generate random data for the wind chart
        for (int i = 0; i < 10; i++) {
            windSpeedData.add(Math.random() * 10);
            windDirectionData.add(Math.random() * 360);
        }

        // Create chart
        XYChart chart = new XYChart(600, 400);
        chart.setTitle("Wind Chart");
        chart.setXAxisTitle("Wind Speed");
        chart.setYAxisTitle("Wind Direction");

        // Add series to the chart
        chart.addSeries("Wind Data", windSpeedData, windDirectionData).setMarker(SeriesMarkers.CIRCLE);

        // Customize the chart style
        chart.getStyler().setLegendPosition(Styler.LegendPosition.InsideNE);

        // Create Panel
        XChartPanel<XYChart> chartPanel = new XChartPanel<>(chart);
        chartPanel.setPreferredSize(new Dimension(560, 370));
        jPanelWindChart.add(chartPanel);
    }

    private void initGanttChart() {
        TaskSeriesCollection dataset = createDataset();

        // Create chart
        JFreeChart chart = ChartFactory.createGanttChart(
                "Inventory",
                "Task",
                "Time",
                dataset,
                true,
                true,
                false
        );

        // Create Panel
        ChartPanel chartPanel = new ChartPanel(chart);
        chartPanel.setPreferredSize(new Dimension(600, 400));
        jPanelGanttChart.add(chartPanel);
    }

    private TaskSeriesCollection createDataset() {
        TaskSeriesCollection dataset = new TaskSeriesCollection();

        // Add tasks to the dataset
        TaskSeries taskSeries1 = new TaskSeries("Orders");
        taskSeries1.add(new Task("Task 1", date(1, 1), date(1, 5)));
        taskSeries1.add(new Task("Task 2", date(2, 1), date(2, 10)));
        taskSeries1.add(new Task("Task 3", date(3, 5), date(3, 15)));

        TaskSeries taskSeries2 = new TaskSeries("Sold");
        taskSeries2.add(new Task("Task A", date(1, 3), date(1, 8)));
        taskSeries2.add(new Task("Task B", date(2, 6), date(2, 12)));

        dataset.add(taskSeries1);
        dataset.add(taskSeries2);

        return dataset;
    }

    private Date date(int day, int month) {
        // This method creates a date for demonstration purposes. In a real application, use a proper date implementation.
        return new Date(2023, month, day);
    }
    
    private void initHistogramChart(){
         HistogramDataset dataset = createDatasetHistogram();

        // Create chart
        JFreeChart chart = ChartFactory.createHistogram(
                "Sample Histogram",
                "Value",
                "Frequency",
                dataset
        );

        // Create Panel
        ChartPanel chartPanel = new ChartPanel(chart);
        chartPanel.setPreferredSize(new Dimension(560, 370));
        jPanelWindChart.add(chartPanel);

    }

    private HistogramDataset createDatasetHistogram() {
        HistogramDataset dataset = new HistogramDataset();
        
        // Generate random data for the histogram
        double[] values = new double[1000];
        for (int i = 0; i < values.length; i++) {
            values[i] = Math.random() * 100;
        }

        // Add the data to the dataset
        dataset.addSeries("Histogram", values, 10); // 10 bins

        return dataset;
    }

}
