/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package com.aldrin.ums.gui.panel;

import com.formdev.flatlaf.FlatClientProperties;
import com.formdev.flatlaf.extras.FlatSVGIcon;
import java.awt.Dimension;
import java.awt.Font;
import javax.swing.JTable;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.JTableHeader;
import javax.swing.table.TableColumn;
import javax.swing.table.TableModel;
import javax.swing.table.TableRowSorter;
import javax.swing.text.StyleConstants;

/**
 *
 * @author ALDRIN B. C.
 */
public class JPanelUser extends javax.swing.JPanel {

    /**
     * Creates new form JPanelUser
     */
    public JPanelUser() {
        initComponents();
        initTable();
        jPanel1.putClientProperty(FlatClientProperties.STYLE,
                "[light]border: 0,0,0,10,shade(@background,30%),,10;" + "[dark]border: 0,0,0,0,tint(@background,30%),,8");

        jPanel15.putClientProperty(FlatClientProperties.STYLE,
                "[light]border: 0,0,0,0,shade(@background,30%),,8;" + "[dark]border: 0,0,0,0,tint(@background,30%),,8");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel27 = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
        jPanel8 = new javax.swing.JPanel();
        jPanel11 = new javax.swing.JPanel();
        jPanel13 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTablePayment = new javax.swing.JTable();
        jPanel17 = new javax.swing.JPanel();
        jPanel18 = new javax.swing.JPanel();
        jPanel19 = new javax.swing.JPanel();
        jPanelButtons = new javax.swing.JPanel();
        jButtonDiscount = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jButtonReturn = new javax.swing.JButton(new FlatSVGIcon("svg/return.svg"));
        jLabel2 = new javax.swing.JLabel();
        jButtonEdit = new javax.swing.JButton();
        jPanelButtons1 = new javax.swing.JPanel();
        jButtonNewDispense = new javax.swing.JButton(new FlatSVGIcon("svg/new.svg"));
        jLabel3 = new javax.swing.JLabel();
        jButtonHold = new javax.swing.JButton(new FlatSVGIcon("svg/hold.svg"));
        jLabel4 = new javax.swing.JLabel();
        jButtonPayment = new javax.swing.JButton(new FlatSVGIcon("svg/paid.svg"));
        jPanel20 = new javax.swing.JPanel();
        jPanel9 = new javax.swing.JPanel();
        jPanel15 = new javax.swing.JPanel();
        jPanel12 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jPanel10 = new javax.swing.JPanel();
        jPanel24 = new javax.swing.JPanel();
        jPanel25 = new javax.swing.JPanel();
        jPanel26 = new javax.swing.JPanel();
        jPanel16 = new javax.swing.JPanel();
        jPanel14 = new javax.swing.JPanel();
        jPanel21 = new javax.swing.JPanel();
        jPanel23 = new javax.swing.JPanel();
        jPanel22 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        jPanel5 = new javax.swing.JPanel();
        jPanel6 = new javax.swing.JPanel();
        jPanel7 = new javax.swing.JPanel();
        jPanel28 = new javax.swing.JPanel();
        jPanel29 = new javax.swing.JPanel();
        jPanel30 = new javax.swing.JPanel();
        jPanel31 = new javax.swing.JPanel();

        setLayout(new java.awt.BorderLayout());

        jPanel27.setLayout(new java.awt.BorderLayout());

        jPanel1.setLayout(new java.awt.BorderLayout());

        jPanel2.setOpaque(false);
        jPanel2.setLayout(new java.awt.BorderLayout());

        jPanel4.setOpaque(false);
        jPanel4.setLayout(new java.awt.BorderLayout());

        jPanel8.setLayout(new java.awt.BorderLayout());

        jPanel11.setLayout(new java.awt.BorderLayout());

        jPanel13.setLayout(new java.awt.BorderLayout());

        jTablePayment.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTablePayment);

        jPanel13.add(jScrollPane1, java.awt.BorderLayout.CENTER);

        jPanel11.add(jPanel13, java.awt.BorderLayout.CENTER);

        jPanel17.setLayout(new java.awt.BorderLayout());

        jPanel18.setLayout(new java.awt.BorderLayout());

        jPanel19.setLayout(new java.awt.BorderLayout());

        jPanelButtons.setPreferredSize(new java.awt.Dimension(350, 80));
        jPanelButtons.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.LEFT, 0, 20));

        jButtonDiscount.setIcon(new FlatSVGIcon("svg/discount.svg"));
        jButtonDiscount.setText("<html><center><u>D</u>iscount<br><h4 style=\"color:red; padding:0; margin:0;\">[F7]</h4></center></html>");
        jButtonDiscount.setMargin(new java.awt.Insets(2, 2, 3, 2));
        jButtonDiscount.setPreferredSize(new java.awt.Dimension(90, 42));
        jPanelButtons.add(jButtonDiscount);

        jLabel1.setText("     ");
        jPanelButtons.add(jLabel1);

        jButtonReturn.setText("<html><center><u>R</u>eturn<br><h4 style=\"color:red; padding:0; margin:0;\">[F6]</h4></center></html>");
        jButtonReturn.setMargin(new java.awt.Insets(2, 2, 3, 2));
        jButtonReturn.setPreferredSize(new java.awt.Dimension(90, 42));
        jPanelButtons.add(jButtonReturn);

        jLabel2.setText("     ");
        jPanelButtons.add(jLabel2);

        jButtonEdit.setIcon(new FlatSVGIcon("svg/update.svg"));
        jButtonEdit.setText("<html><center><u>E</u>dit Quantity<br><h4 style=\"color:red; padding:0; margin:0;\">[F5]</h4></center></html>");
        jButtonEdit.setMargin(new java.awt.Insets(2, 2, 3, 2));
        jButtonEdit.setPreferredSize(new java.awt.Dimension(105, 42));
        jPanelButtons.add(jButtonEdit);

        jPanel19.add(jPanelButtons, java.awt.BorderLayout.WEST);

        jPanelButtons1.setPreferredSize(new java.awt.Dimension(350, 80));
        jPanelButtons1.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.RIGHT, 0, 20));

        jButtonNewDispense.setText("<html><center><u>N</u>ew Dispense<br><h4 style=\"color:red; padding:0; margin:0;\">[F1]</h4></center></html>");
        jButtonNewDispense.setMargin(new java.awt.Insets(2, 2, 3, 2));
        jButtonNewDispense.setPreferredSize(new java.awt.Dimension(110, 42));
        jPanelButtons1.add(jButtonNewDispense);

        jLabel3.setText("     ");
        jPanelButtons1.add(jLabel3);

        jButtonHold.setIcon(new FlatSVGIcon("svg/hold.svg"));
        jButtonHold.setText("<html><centee><u>H</u>old<br><h4 style=\"color:red; padding:0; margin:0;\">[F2]</h4></center></html>");
        jButtonHold.setMargin(new java.awt.Insets(2, 2, 3, 2));
        jButtonHold.setPreferredSize(new java.awt.Dimension(90, 42));
        jPanelButtons1.add(jButtonHold);

        jLabel4.setText("     ");
        jPanelButtons1.add(jLabel4);

        jButtonPayment.setIcon(new FlatSVGIcon("svg/paid.svg"));
        jButtonPayment.setText("<html><center><u>P</u>ayment<br><h4 style=\"color:red; padding:0; margin:0;\">[Space]</h4></center></html>");
        jButtonPayment.setMargin(new java.awt.Insets(2, 2, 3, 2));
        jButtonPayment.setPreferredSize(new java.awt.Dimension(90, 42));
        jPanelButtons1.add(jButtonPayment);

        jPanel19.add(jPanelButtons1, java.awt.BorderLayout.CENTER);

        jPanel18.add(jPanel19, java.awt.BorderLayout.CENTER);

        jPanel17.add(jPanel18, java.awt.BorderLayout.CENTER);

        jPanel20.setPreferredSize(new java.awt.Dimension(798, 5));

        javax.swing.GroupLayout jPanel20Layout = new javax.swing.GroupLayout(jPanel20);
        jPanel20.setLayout(jPanel20Layout);
        jPanel20Layout.setHorizontalGroup(
            jPanel20Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 768, Short.MAX_VALUE)
        );
        jPanel20Layout.setVerticalGroup(
            jPanel20Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 5, Short.MAX_VALUE)
        );

        jPanel17.add(jPanel20, java.awt.BorderLayout.NORTH);

        jPanel11.add(jPanel17, java.awt.BorderLayout.SOUTH);

        jPanel8.add(jPanel11, java.awt.BorderLayout.CENTER);

        jPanel4.add(jPanel8, java.awt.BorderLayout.CENTER);

        jPanel9.setPreferredSize(new java.awt.Dimension(889, 60));
        jPanel9.setLayout(new java.awt.BorderLayout());

        jPanel15.setLayout(new java.awt.BorderLayout());

        jPanel12.setLayout(new java.awt.BorderLayout());

        jLabel5.setFont(new java.awt.Font("Courier New", 0, 24)); // NOI18N
        jLabel5.setText("TOTAL:");
        jPanel12.add(jLabel5, java.awt.BorderLayout.WEST);

        jLabel6.setFont(new java.awt.Font("Courier New", 0, 48)); // NOI18N
        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel6.setText("0.00");
        jPanel12.add(jLabel6, java.awt.BorderLayout.CENTER);

        jPanel15.add(jPanel12, java.awt.BorderLayout.CENTER);

        jPanel10.setOpaque(false);
        jPanel10.setPreferredSize(new java.awt.Dimension(518, 5));

        javax.swing.GroupLayout jPanel10Layout = new javax.swing.GroupLayout(jPanel10);
        jPanel10.setLayout(jPanel10Layout);
        jPanel10Layout.setHorizontalGroup(
            jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 318, Short.MAX_VALUE)
        );
        jPanel10Layout.setVerticalGroup(
            jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 5, Short.MAX_VALUE)
        );

        jPanel15.add(jPanel10, java.awt.BorderLayout.NORTH);

        jPanel24.setOpaque(false);
        jPanel24.setPreferredSize(new java.awt.Dimension(518, 5));

        javax.swing.GroupLayout jPanel24Layout = new javax.swing.GroupLayout(jPanel24);
        jPanel24.setLayout(jPanel24Layout);
        jPanel24Layout.setHorizontalGroup(
            jPanel24Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 318, Short.MAX_VALUE)
        );
        jPanel24Layout.setVerticalGroup(
            jPanel24Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 5, Short.MAX_VALUE)
        );

        jPanel15.add(jPanel24, java.awt.BorderLayout.SOUTH);

        jPanel25.setOpaque(false);
        jPanel25.setPreferredSize(new java.awt.Dimension(5, 45));

        javax.swing.GroupLayout jPanel25Layout = new javax.swing.GroupLayout(jPanel25);
        jPanel25.setLayout(jPanel25Layout);
        jPanel25Layout.setHorizontalGroup(
            jPanel25Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 5, Short.MAX_VALUE)
        );
        jPanel25Layout.setVerticalGroup(
            jPanel25Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 45, Short.MAX_VALUE)
        );

        jPanel15.add(jPanel25, java.awt.BorderLayout.EAST);

        jPanel26.setOpaque(false);
        jPanel26.setPreferredSize(new java.awt.Dimension(5, 45));

        javax.swing.GroupLayout jPanel26Layout = new javax.swing.GroupLayout(jPanel26);
        jPanel26.setLayout(jPanel26Layout);
        jPanel26Layout.setHorizontalGroup(
            jPanel26Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 5, Short.MAX_VALUE)
        );
        jPanel26Layout.setVerticalGroup(
            jPanel26Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 45, Short.MAX_VALUE)
        );

        jPanel15.add(jPanel26, java.awt.BorderLayout.LINE_START);

        jPanel9.add(jPanel15, java.awt.BorderLayout.CENTER);

        jPanel16.setPreferredSize(new java.awt.Dimension(1048, 5));

        javax.swing.GroupLayout jPanel16Layout = new javax.swing.GroupLayout(jPanel16);
        jPanel16.setLayout(jPanel16Layout);
        jPanel16Layout.setHorizontalGroup(
            jPanel16Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 768, Short.MAX_VALUE)
        );
        jPanel16Layout.setVerticalGroup(
            jPanel16Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 5, Short.MAX_VALUE)
        );

        jPanel9.add(jPanel16, java.awt.BorderLayout.SOUTH);

        jPanel14.setPreferredSize(new java.awt.Dimension(450, 55));
        jPanel14.setLayout(new java.awt.BorderLayout());

        jPanel21.setPreferredSize(new java.awt.Dimension(250, 20));

        javax.swing.GroupLayout jPanel21Layout = new javax.swing.GroupLayout(jPanel21);
        jPanel21.setLayout(jPanel21Layout);
        jPanel21Layout.setHorizontalGroup(
            jPanel21Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 450, Short.MAX_VALUE)
        );
        jPanel21Layout.setVerticalGroup(
            jPanel21Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 20, Short.MAX_VALUE)
        );

        jPanel14.add(jPanel21, java.awt.BorderLayout.NORTH);

        jPanel23.setLayout(new java.awt.BorderLayout());
        jPanel14.add(jPanel23, java.awt.BorderLayout.CENTER);

        jPanel22.setPreferredSize(new java.awt.Dimension(5, 35));

        javax.swing.GroupLayout jPanel22Layout = new javax.swing.GroupLayout(jPanel22);
        jPanel22.setLayout(jPanel22Layout);
        jPanel22Layout.setHorizontalGroup(
            jPanel22Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 5, Short.MAX_VALUE)
        );
        jPanel22Layout.setVerticalGroup(
            jPanel22Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 35, Short.MAX_VALUE)
        );

        jPanel14.add(jPanel22, java.awt.BorderLayout.WEST);

        jPanel9.add(jPanel14, java.awt.BorderLayout.EAST);

        jPanel4.add(jPanel9, java.awt.BorderLayout.PAGE_START);

        jPanel2.add(jPanel4, java.awt.BorderLayout.CENTER);

        jPanel1.add(jPanel2, java.awt.BorderLayout.CENTER);

        jPanel3.setOpaque(false);
        jPanel3.setPreferredSize(new java.awt.Dimension(5, 435));

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 5, Short.MAX_VALUE)
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 370, Short.MAX_VALUE)
        );

        jPanel1.add(jPanel3, java.awt.BorderLayout.EAST);

        jPanel5.setOpaque(false);
        jPanel5.setPreferredSize(new java.awt.Dimension(899, 5));

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 778, Short.MAX_VALUE)
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 5, Short.MAX_VALUE)
        );

        jPanel1.add(jPanel5, java.awt.BorderLayout.NORTH);

        jPanel6.setOpaque(false);
        jPanel6.setPreferredSize(new java.awt.Dimension(899, 5));

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 778, Short.MAX_VALUE)
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 5, Short.MAX_VALUE)
        );

        jPanel1.add(jPanel6, java.awt.BorderLayout.SOUTH);

        jPanel7.setOpaque(false);
        jPanel7.setPreferredSize(new java.awt.Dimension(5, 425));

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 5, Short.MAX_VALUE)
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 370, Short.MAX_VALUE)
        );

        jPanel1.add(jPanel7, java.awt.BorderLayout.LINE_START);

        jPanel27.add(jPanel1, java.awt.BorderLayout.CENTER);

        jPanel28.setOpaque(false);
        jPanel28.setPreferredSize(new java.awt.Dimension(811, 5));

        javax.swing.GroupLayout jPanel28Layout = new javax.swing.GroupLayout(jPanel28);
        jPanel28.setLayout(jPanel28Layout);
        jPanel28Layout.setHorizontalGroup(
            jPanel28Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 788, Short.MAX_VALUE)
        );
        jPanel28Layout.setVerticalGroup(
            jPanel28Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 5, Short.MAX_VALUE)
        );

        jPanel27.add(jPanel28, java.awt.BorderLayout.NORTH);

        jPanel29.setOpaque(false);
        jPanel29.setPreferredSize(new java.awt.Dimension(811, 5));

        javax.swing.GroupLayout jPanel29Layout = new javax.swing.GroupLayout(jPanel29);
        jPanel29.setLayout(jPanel29Layout);
        jPanel29Layout.setHorizontalGroup(
            jPanel29Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 788, Short.MAX_VALUE)
        );
        jPanel29Layout.setVerticalGroup(
            jPanel29Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 5, Short.MAX_VALUE)
        );

        jPanel27.add(jPanel29, java.awt.BorderLayout.SOUTH);

        jPanel30.setOpaque(false);
        jPanel30.setPreferredSize(new java.awt.Dimension(5, 584));

        javax.swing.GroupLayout jPanel30Layout = new javax.swing.GroupLayout(jPanel30);
        jPanel30.setLayout(jPanel30Layout);
        jPanel30Layout.setHorizontalGroup(
            jPanel30Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 5, Short.MAX_VALUE)
        );
        jPanel30Layout.setVerticalGroup(
            jPanel30Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 380, Short.MAX_VALUE)
        );

        jPanel27.add(jPanel30, java.awt.BorderLayout.LINE_END);

        jPanel31.setOpaque(false);
        jPanel31.setPreferredSize(new java.awt.Dimension(5, 584));

        javax.swing.GroupLayout jPanel31Layout = new javax.swing.GroupLayout(jPanel31);
        jPanel31.setLayout(jPanel31Layout);
        jPanel31Layout.setHorizontalGroup(
            jPanel31Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 5, Short.MAX_VALUE)
        );
        jPanel31Layout.setVerticalGroup(
            jPanel31Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 380, Short.MAX_VALUE)
        );

        jPanel27.add(jPanel31, java.awt.BorderLayout.LINE_START);

        add(jPanel27, java.awt.BorderLayout.CENTER);
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonDiscount;
    private javax.swing.JButton jButtonEdit;
    private javax.swing.JButton jButtonHold;
    private javax.swing.JButton jButtonNewDispense;
    private javax.swing.JButton jButtonPayment;
    private javax.swing.JButton jButtonReturn;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel10;
    private javax.swing.JPanel jPanel11;
    private javax.swing.JPanel jPanel12;
    private javax.swing.JPanel jPanel13;
    private javax.swing.JPanel jPanel14;
    private javax.swing.JPanel jPanel15;
    private javax.swing.JPanel jPanel16;
    private javax.swing.JPanel jPanel17;
    private javax.swing.JPanel jPanel18;
    private javax.swing.JPanel jPanel19;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel20;
    private javax.swing.JPanel jPanel21;
    private javax.swing.JPanel jPanel22;
    private javax.swing.JPanel jPanel23;
    private javax.swing.JPanel jPanel24;
    private javax.swing.JPanel jPanel25;
    private javax.swing.JPanel jPanel26;
    private javax.swing.JPanel jPanel27;
    private javax.swing.JPanel jPanel28;
    private javax.swing.JPanel jPanel29;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel30;
    private javax.swing.JPanel jPanel31;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JPanel jPanel9;
    private javax.swing.JPanel jPanelButtons;
    private javax.swing.JPanel jPanelButtons1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTablePayment;
    // End of variables declaration//GEN-END:variables

    public DefaultTableModel tableModelSearch = new DefaultTableModel() {
        public Class getColumnClass(int columnIndex) {
            if (columnIndex == 0) {
                return String.class;
            }
            switch (columnIndex) {
                case 1:
                    return String.class;
                case 2:
                    return String.class;
                case 3:
                    return Integer.class;
                default:
                    return String.class;
            }
        }

        public boolean isCellEditable(int row, int col) {
            if (col < 10) {
                return false;

            } else {
                return false;
            }
        }
    };
    private TableRowSorter<TableModel> sorter = new TableRowSorter<TableModel>(tableModelSearch);

    private void initTable() {
        try {
            String[] columnNames = {
                "ID",//
                "PRODUCT",//1
                "UNIT",//2
                "QUANTITY",
                "UNIT PRICE",
                "LINE TOTAL"
            };//15

            jTablePayment.setCellSelectionEnabled(true);
            jTablePayment = new JTable(tableModelSearch);
            JTableHeader header = jTablePayment.getTableHeader();
            header.setPreferredSize(new Dimension(100, 35));
            header.setFont(new Font("Courier New", Font.PLAIN, 16));
//            header.setBackground(new java.awt.Color(0, 102, 153));
//            header.setForeground(new java.awt.Color(0, 102, 153));
            jTablePayment.setRowSorter(sorter);
//            jTableSearch.addMouseListener(this);
            jTablePayment.setRowHeight(30);
            jTablePayment.setFont(new Font("Courier New", Font.PLAIN, 18));
            jScrollPane1.setViewportView(jTablePayment);
            for (int i = 0; i < columnNames.length;) {
                tableModelSearch.addColumn(columnNames[i]);
                i++;
            }
            jScrollPane1.setViewportView(jTablePayment);

            TableColumn[] column = new TableColumn[100];

            column[0] = jTablePayment.getColumnModel().getColumn(0);
            column[0].setPreferredWidth(40);

            column[1] = jTablePayment.getColumnModel().getColumn(1);
            column[1].setPreferredWidth(300);

            column[2] = jTablePayment.getColumnModel().getColumn(2);
            column[2].setPreferredWidth(110);

            TableColumn hidden1 = jTablePayment.getColumnModel().getColumn(0);
            hidden1.setMinWidth(0);
            hidden1.setPreferredWidth(0);
            hidden1.setMaxWidth(0);

        } catch (Exception e) {
            e.printStackTrace();
        }

    }

}
